# bash completion for {{PROG}}, generated by `{{PROG}} completion bash`.
# Load it into the current shell:  source <({{PROG}} completion bash)
# Load it in every shell: add that line to ~/.bashrc. Requires bash 4.4 or later.

# Rebuilds the command words that readline split at ':' and '=' (both are in
# COMP_WORDBREAKS), so that values such as project:issue stay one word.
__{{ID}}_words() {
    local line=$COMP_LINE word i blank
    words=() cword=0
    for ((i = 0; i < ${#COMP_WORDS[@]}; i++)); do
        word=${COMP_WORDS[i]}
        blank=0
        [[ $line == [[:blank:]]* ]] && blank=1
        line=${line#"${line%%[![:blank:]]*}"}
        line=${line#"$word"}
        if ((i > 0 && !blank)) && [[ $word == [:=]* || ${words[-1]} == *[:=] ]]; then
            words[-1]+=$word
        else
            words+=("$word")
        fi
        ((i == COMP_CWORD)) && cword=$((${#words[@]} - 1))
    done
}

# Prints a word as the shell would pass it, without expanding anything; an
# unterminated quote counts as closed.
__{{ID}}_dequote() {
    local word=$1 out= quote= c i
    for ((i = 0; i < ${#word}; i++)); do
        c=${word:i:1}
        if [[ $quote == "'" ]]; then
            if [[ $c == "'" ]]; then quote=; else out+=$c; fi
        elif [[ $c == '\' ]]; then
            ((i++))
            c=${word:i:1}
            [[ $quote == '"' && $c != [\$\`\"\\] ]] && out+='\'
            out+=$c
        elif [[ $c == "'" && -z $quote ]]; then
            quote="'"
        elif [[ $c == '"' ]]; then
            if [[ $quote ]]; then quote=; else quote='"'; fi
        else
            out+=$c
        fi
    done
    printf '%s' "$out"
}

# Prints a candidate as the text that replaces the word being completed: in
# the quote the word opened, otherwise with backslash escapes.
__{{ID}}_quote() {
    local value=$1
    case $2 in
    "'") printf "'%s'" "${value//\'/\'\\\'\'}" ;;
    '"')
        value=${value//\\/\\\\}
        value=${value//\"/\\\"}
        value=${value//\$/\\\$}
        value=${value//\`/\\\`}
        printf '"%s"' "$value"
        ;;
    *) printf '%q' "$value" ;;
    esac
}

_{{ID}}() {
    local -a words args lines
    local cword i current opened= directive=1 skip line
    __{{ID}}_words
    current=${words[cword]}
    [[ $current == [\'\"]* ]] && opened=${current:0:1}
    for ((i = 1; i <= cword; i++)); do
        args+=("$(__{{ID}}_dequote "${words[i]}")")
    done
    mapfile -t lines < <("$(__{{ID}}_dequote "${words[0]}")" {{COMPLETE}} "${args[@]}" 2>/dev/null)
    if ((${#lines[@]})) && [[ ${lines[-1]} =~ ^:([0-9]+)$ ]]; then
        directive=${BASH_REMATCH[1]}
        unset 'lines[-1]'
    fi
    COMPREPLY=()
    ((directive & 1)) && return
    ((directive & 2)) && compopt -o nospace
    ((directive & 32)) && compopt -o nosort
    if ((directive & 16)); then
        compopt -o filenames
        mapfile -t COMPREPLY < <(compgen -d -- "${args[-1]}")
        return
    fi
    # Readline replaces only the text after the last ':' or '=' outside quotes.
    [[ $opened ]] || skip=${current%"${current##*[:=]}"}
    for line in "${lines[@]}"; do
        line=$(__{{ID}}_quote "${line%%$'\t'*}" "$opened")
        COMPREPLY+=("${line#"$skip"}")
    done
    ((${#COMPREPLY[@]} == 0 && !(directive & 4))) && compopt -o default
    return 0
}

complete -F _{{ID}} {{PROG}}
