# fish completion for {{PROG}}, generated by `{{PROG}} completion fish`.
# Load it into the current shell:  {{PROG}} completion fish | source
# Load it in every shell: save it as ~/.config/fish/completions/{{PROG}}.fish

# Asks {{PROG}} for the candidates: the words before the cursor (unquoted, not
# expanded) and the word being completed. The last line is the directive.
function __{{ID}}_request
    set -l words (commandline -opc)
    set -l current (string unescape -- (commandline -ct) 2>/dev/null; or commandline -ct)
    set -g __{{ID}}_results ($words[1] {{COMPLETE}} $words[2..-1] "$current" 2>/dev/null)
    set -g __{{ID}}_directive 1
    if string match -qr '^:[0-9]+$' -- "$__{{ID}}_results[-1]"
        set -g __{{ID}}_directive (string sub -s 2 -- $__{{ID}}_results[-1])
        set -e __{{ID}}_results[-1]
    end
end

function __{{ID}}_has
    test (math --scale 0 "$__{{ID}}_directive / $argv[1] % 2") -eq 1
end

# Registered first, so it runs first for each completion: forget the last answer.
function __{{ID}}_reset
    set -e __{{ID}}_requested
    return 1
end

# True when the candidates apply; false lets fish complete file names.
function __{{ID}}_ready
    if not set -q __{{ID}}_requested
        set -g __{{ID}}_requested
        __{{ID}}_request
        if __{{ID}}_has 1
            set -g __{{ID}}_results
        else if __{{ID}}_has 16
            set -g __{{ID}}_results (__fish_complete_directories (commandline -ct))
        end
    end
    __{{ID}}_has 1; or __{{ID}}_has 4; or __{{ID}}_has 16; or test (count $__{{ID}}_results) -gt 0
end

function __{{ID}}_ordered
    __{{ID}}_ready; and __{{ID}}_has 32
end

complete -c {{PROG}} -e
complete -c {{PROG}} -n __{{ID}}_reset
complete -c {{PROG}} -n __{{ID}}_ordered -k -f -a '$__{{ID}}_results'
complete -c {{PROG}} -n 'not __{{ID}}_ordered; and __{{ID}}_ready' -f -a '$__{{ID}}_results'
