#compdef {{PROG}}
# zsh completion for {{PROG}}, generated by `{{PROG}} completion zsh`.
# Load it into the current shell (after compinit):  source <({{PROG}} completion zsh)
# Load it in every shell: save it as _{{PROG}} in a directory on $fpath.

_{{ID}}() {
    local -a lines values displays group
    local line value directive=1 width=0
    lines=("${(@f)$(${(Q)words[1]} {{COMPLETE}} "${(@Q)words[2,CURRENT-1]}" "$PREFIX" 2>/dev/null)}")
    if [[ ${lines[-1]} == :<-> ]]; then
        directive=${lines[-1]#:}
        lines=("${(@)lines[1,-2]}")
    fi
    (( directive & 1 )) && return 1
    if (( directive & 16 )); then
        _path_files -/
        return
    fi
    for line in "${lines[@]}"; do
        [[ -n $line ]] || continue
        values+=("${line%%$'\t'*}")
        (( width = ${#values[-1]} > width ? ${#values[-1]} : width ))
    done
    if (( ${#values} == 0 )); then
        (( directive & 4 )) || _files
        return
    fi
    for line in "${lines[@]}"; do
        [[ -n $line ]] || continue
        value=${line%%$'\t'*}
        if [[ $line == *$'\t'* ]]; then
            displays+=("${(r:width:)value}  -- ${line#*$'\t'}")
        else
            displays+=("$value")
        fi
    done
    group=(-J {{ID}})
    (( directive & 32 )) && group=(-V {{ID}})
    (( directive & 2 )) && group+=(-S '')
    compadd "${group[@]}" -l -d displays -- "${values[@]}"
}

if [[ $funcstack[1] == _{{PROG}} ]]; then
    _{{ID}} "$@"
else
    compdef _{{ID}} {{PROG}}
fi
