package cli

import (
	"fmt"
	"github.com/nerdwave-nick/nerdwave-workflows/internal/nwcli"
	"github.com/nerdwave-nick/nerdwave-workflows/internal/protocol"
	"io"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"
)

func parseProjectArgs(argv []string, a Args) (Args, error) {
	seenCommand, seenVerb := false, false
	group := map[string][]string{}
	a.Groups = append(a.Groups, group)
	cmd := grammar.Find("projects", a.Verb)
	if a.Verb == "" || cmd == nil {
		return a, fmt.Errorf("expected projects create, get, list, update, or history")
	}
	for i := 0; i < len(argv); i++ {
		v := argv[i]
		if v == "--" {
			a.Positionals = append(a.Positionals, argv[i+1:]...)
			break
		}
		v = cmd.ExpandShort(v)
		if len(v) > 1 && v[0] == '-' && v[1] != '-' {
			return a, fmt.Errorf("unknown flag %s", v)
		}
		if !strings.HasPrefix(v, "--") {
			if !seenCommand && v == "projects" {
				seenCommand = true
				continue
			}
			if !seenVerb && v == a.Verb {
				seenVerb = true
				continue
			}
			a.Positionals = append(a.Positionals, v)
			continue
		}
		parts := strings.SplitN(strings.TrimPrefix(v, "--"), "=", 2)
		k := parts[0]
		f, owner, ok := cmd.Lookup(k)
		valueNeeded := !f.Switch
		if !ok {
			return a, fmt.Errorf("unknown flag --%s", k)
		}
		value := "true"
		if valueNeeded {
			if len(parts) == 2 {
				value = parts[1]
			} else {
				i++
				if i >= len(argv) || strings.HasPrefix(argv[i], "--") {
					return a, fmt.Errorf("missing value for --%s", k)
				}
				value = argv[i]
			}
		} else if len(parts) > 1 {
			return a, fmt.Errorf("--%s takes no value", k)
		}
		dst := a.Values
		if owner != nil || cmd.StartsItem(k) || !cmd.HasItems() && !invocationFlags[k] {
			if cmd.StartsItem(k) {
				group = map[string][]string{}
				a.Groups = append(a.Groups, group)
			}
			dst = group
		}
		if len(dst[k]) > 0 && f.Repeat != nwcli.Many {
			return a, fmt.Errorf("duplicate flag --%s", k)
		}
		dst[k] = append(dst[k], value)
	}
	if len(a.Groups[0]) == 0 {
		a.Groups = a.Groups[1:]
	}
	if a.Has("file") && (len(a.Groups) > 0 || len(a.Positionals) > 0) {
		return a, fmt.Errorf("file conflicts with explicit inputs")
	}
	if a.Has("format") && !validOutputFormat(a.One("format")) {
		return a, fmt.Errorf("invalid format")
	}
	if a.Verb == "create" && len(a.Positionals) > 0 {
		return a, fmt.Errorf("create uses --project-title")
	}
	if a.Verb == "list" && len(a.Positionals) > 0 {
		return a, fmt.Errorf("list does not accept targets")
	}
	if a.Verb == "history" && len(a.Positionals) > 1 {
		return a, fmt.Errorf("history requires one owner")
	}
	stdinUses := 0
	if a.One("file") == "-" {
		stdinUses++
	}
	for _, g := range a.Groups {
		if len(g["content-file"]) > 0 && g["content-file"][0] == "-" {
			stdinUses++
		}
	}
	if stdinUses > 1 {
		return a, fmt.Errorf("stdin may be consumed only once")
	}
	if a.Has("timeout") {
		d, e := time.ParseDuration(a.One("timeout"))
		if e != nil || d <= 0 {
			return a, fmt.Errorf("timeout must be positive")
		}
	}
	return a, nil
}
func (a *App) projectInputs() ([]protocol.ProjectInput, error) {
	var items []protocol.ProjectInput
	if a.Args.Has("file") {
		b, e := readUTF8(a.Args.One("file"))
		if e != nil {
			return nil, e
		}
		if e = protocol.Decode(b, &items); e != nil {
			return nil, e
		}
		for i := range items {
			if e := items[i].ValidateShape(a.Args.Verb); e != nil {
				return nil, e
			}
			if a.Args.Verb == "create" {
				if items[i].ID != "" || items[i].Fields["id"] {
					return nil, fmt.Errorf("creation IDs are generated by the client")
				}
				items[i].ID = protocol.UUID()
			}
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("empty mutation batch")
		}
		return items, nil
	}
	for _, g := range a.Args.Groups {
		one := func(k string) string {
			if len(g[k]) > 0 {
				return g[k][0]
			}
			return ""
		}
		item := protocol.ProjectInput{}
		var content *string
		if _, ok := g["content"]; ok {
			x := one("content")
			content = &x
		}
		if _, ok := g["content-file"]; ok {
			if content != nil {
				return nil, fmt.Errorf("content and content-file conflict")
			}
			b, e := readUTF8(one("content-file"))
			if e != nil {
				return nil, e
			}
			x := string(b)
			content = &x
		}
		if a.Args.Verb == "create" {
			title := one("project-title")
			if title == "" {
				return nil, fmt.Errorf("each create group needs --project-title")
			}
			item.ID = protocol.UUID()
			item.Title = &title
			item.Content = content
			item.RepositoryRefs = g["repository"]
			items = append(items, item)
			continue
		}
		item.Set.Description = content
		if _, ok := g["title"]; ok {
			title := one("title")
			item.Set.Title = &title
		}
		item.Add.RepositoryRefs = g["add-repository"]
		item.Remove.RepositoryRefs = g["remove-repository"]
		item.Clear = g["clear"]
		if _, ok := g["revision"]; ok {
			n, e := strconv.ParseInt(one("revision"), 10, 64)
			if e != nil || n < 1 {
				return nil, fmt.Errorf("revision must be a positive integer")
			}
			item.ExpectedRevision = &n
		}
		target := one("project-id")
		if target != "" {
			if len(a.Args.Positionals) > 0 {
				return nil, fmt.Errorf("grouped and positional targets conflict")
			}
			item.Target = target
			items = append(items, item)
		} else {
			if len(a.Args.Groups) != 1 {
				return nil, fmt.Errorf("each update group needs --project-id")
			}
			targets := a.Args.Positionals
			if len(targets) == 0 {
				selected, e := a.selectedProject()
				if e != nil {
					return nil, e
				}
				targets = []string{selected}
			}
			for _, target := range targets {
				x := item
				x.Target = target
				items = append(items, x)
			}
		}
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("empty mutation batch")
	}
	return items, nil
}
func readUTF8(path string) ([]byte, error) {
	var b []byte
	var e error
	if path == "-" {
		b, e = io.ReadAll(io.LimitReader(os.Stdin, 32<<20+1))
		if len(b) > 32<<20 {
			return nil, fmt.Errorf("input exceeds request limit")
		}
	} else {
		b, e = os.ReadFile(path)
	}
	if e != nil {
		return nil, e
	}
	if !utf8.Valid(b) {
		return nil, fmt.Errorf("file must be valid UTF-8")
	}
	return b, nil
}
func (a *App) selectedProject() (string, error) {
	if a.Args.Has("project") {
		return a.Args.One("project"), nil
	}
	if a.Client.ProjectID != nil {
		return *a.Client.ProjectID, nil
	}
	return "", fmt.Errorf("select a project explicitly or in session state")
}
func (a *App) projects() (Result, error) {
	result := Result{}
	switch a.Args.Verb {
	case "create", "update":
		items, e := a.projectInputs()
		if e != nil {
			return result, protocol.E(400, "invalid_arguments", e.Error())
		}
		var plan protocol.Prepared
		req := protocol.PrepareRequest{SchemaVersion: 1, Operation: "project." + a.Args.Verb, Items: items}
		if e = a.Call("POST", "/v1/transaction-previews", req, nil, &plan, false); e != nil {
			return result, e
		}
		b, hash, e := protocol.Canonical(plan.Intent)
		if e != nil || hash != plan.RequestHash || plan.SchemaVersion != 1 || plan.ServiceID != a.Meta.ServiceID || plan.ClientID != a.Client.ClientID || string(b) != plan.CanonicalJSON {
			return result, protocol.E(500, "invalid_response", "invalid prepared transaction")
		}
		var v protocol.MutationResult
		if e = a.Call("POST", "/v1/transactions", protocol.DurableRequest{SchemaVersion: 1, Intent: plan.Intent, RequestHash: hash, Claims: preparedTokens(plan)}, nil, &v, true); e != nil {
			return result, e
		}
		result.Outcome = v.Outcome
		result.RequestHash = v.RequestHash
		for _, item := range v.Items {
			result.Items = append(result.Items, item)
		}
		return result, nil
	case "get":
		targets := a.Args.Positionals
		if len(targets) == 0 {
			selected, e := a.selectedProject()
			if e != nil {
				return result, protocol.E(400, "invalid_arguments", e.Error())
			}
			targets = []string{selected}
		}
		typed := []map[string]string{}
		for _, target := range targets {
			typed = append(typed, map[string]string{"type": "projects", "selector": target})
		}
		e := a.Call("POST", "/v1/snapshots", map[string]any{"schema_version": 1, "targets": typed}, nil, &result, false)
		return result, e
	case "list":
		q := map[string]any{"type": "projects"}
		if a.Args.Has("file") {
			b, e := readUTF8(a.Args.One("file"))
			if e != nil {
				return result, protocol.E(400, "invalid_arguments", e.Error())
			}
			if e = protocol.Decode(b, &q); e != nil {
				return result, protocol.E(400, "invalid_arguments", e.Error())
			}
			if _, ok := q["type"]; !ok {
				q["type"] = "projects"
			}
		}
		for _, g := range a.Args.Groups {
			for k, v := range g {
				switch k {
				case "all":
					q[k] = true
				case "limit":
					n, e := strconv.Atoi(v[0])
					if e != nil {
						return result, protocol.E(400, "invalid_arguments", "invalid limit")
					}
					q[k] = n
				default:
					if e := a.queryValue(q, k, v, ""); e != nil {
						return result, protocol.E(400, "invalid_arguments", e.Error())
					}
				}
			}
		}
		e := a.Call("POST", "/v1/snapshots", map[string]any{"schema_version": 1, "query": q}, nil, &result, false)
		return result, e
	case "history":
		target := ""
		if len(a.Args.Positionals) > 0 {
			target = a.Args.Positionals[0]
		} else {
			var e error
			target, e = a.selectedProject()
			if e != nil {
				return result, protocol.E(400, "invalid_arguments", e.Error())
			}
		}
		var p protocol.Project
		if e := a.Call("GET", "/v1/projects/"+url.PathEscape(target), nil, nil, &p, false); e != nil {
			return result, e
		}
		path := "/v1/projects/" + p.ID + "/history"
		hash := ""
		for _, g := range a.Args.Groups {
			if len(g["request-hash"]) > 0 {
				hash = g["request-hash"][0]
			}
		}
		if hash != "" {
			var v any
			e := a.Call("GET", path+"/"+url.PathEscape(hash), nil, nil, &v, false)
			result.Items = []any{v}
			return result, e
		}
		query := url.Values{}
		for _, group := range a.Args.Groups {
			for key, values := range group {
				if key != "request-hash" {
					query.Set(key, values[0])
				}
			}
		}
		if len(query) > 0 {
			path += "?" + query.Encode()
		}
		e := a.Call("GET", path, nil, nil, &result, false)
		return result, e
	}
	return result, protocol.E(400, "invalid_arguments", "unknown project verb")
}
